/* Klimbora 19b993250a - generated by build-www.mjs, do not edit */
const CACHE = 'klimbora-19b993250a';
const SHELL = [
  "./",
  "index.html",
  "manifest.json",
  "apple-touch-icon.png",
  "icons/icon-128.webp",
  "icons/icon-192.webp",
  "icons/icon-256.webp",
  "icons/icon-48.webp",
  "icons/icon-512.webp",
  "icons/icon-72.webp",
  "icons/icon-96.webp",
  "fonts/Baloo2-700-wXKrE3kTposypRyd51bcANwr.woff2",
  "fonts/Baloo2-700-wXKrE3kTposypRyd51jcAA.woff2",
  "fonts/Baloo2-800-wXKrE3kTposypRyd51bcANwr.woff2",
  "fonts/Baloo2-800-wXKrE3kTposypRyd51jcAA.woff2",
  "fonts/Nunito-700-XRXV3I6Li01BKofINeaB.woff2",
  "fonts/Nunito-700-XRXV3I6Li01BKofIO-aBXso.woff2",
  "fonts/Nunito-800-XRXV3I6Li01BKofINeaB.woff2",
  "fonts/Nunito-800-XRXV3I6Li01BKofIO-aBXso.woff2",
  "fonts/Nunito-900-XRXV3I6Li01BKofINeaB.woff2",
  "fonts/Nunito-900-XRXV3I6Li01BKofIO-aBXso.woff2"
];
self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(k => Promise.all(k.filter(n => n !== CACHE).map(n => caches.delete(n))))
    .then(() => self.clients.claim()));
});
// cache first: the game is one file and never talks to a server
self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true })
    .then(hit => hit || fetch(e.request)));
});
