/* Klimbora 7def84532c - generated by tools/build-site.mjs, do not edit */
const CACHE = 'klimbora-7def84532c';
const SHELL = [
  "./",
  "index.html",
  "manifest.json",
  "apple-touch-icon.png",
  "icons/icon-192.png",
  "icons/icon-256.png",
  "icons/icon-384.png",
  "icons/icon-512.png",
  "fonts/Baloo2-700-wXKrE3kTposypRyd51bcANwr.woff2",
  "fonts/Baloo2-700-wXKrE3kTposypRyd51jcAA.woff2",
  "fonts/Baloo2-800-wXKrE3kTposypRyd51bcANwr.woff2",
  "fonts/Baloo2-800-wXKrE3kTposypRyd51jcAA.woff2",
  "fonts/Nunito-700-XRXV3I6Li01BKofINeaB.woff2",
  "fonts/Nunito-700-XRXV3I6Li01BKofIO-aBXso.woff2",
  "fonts/Nunito-800-XRXV3I6Li01BKofINeaB.woff2",
  "fonts/Nunito-800-XRXV3I6Li01BKofIO-aBXso.woff2",
  "fonts/Nunito-900-XRXV3I6Li01BKofINeaB.woff2",
  "fonts/Nunito-900-XRXV3I6Li01BKofIO-aBXso.woff2",
  "assets/scenes/aurora.webp",
  "assets/scenes/beach.webp",
  "assets/scenes/canyon.webp",
  "assets/scenes/city.webp",
  "assets/scenes/dunes.webp",
  "assets/scenes/peaks.webp",
  "assets/scenes/redwood.webp",
  "assets/scenes/reef.webp",
  "assets/scenes/space.webp",
  "assets/scenes/valley.webp"
];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(k => Promise.all(k.filter(n => n !== CACHE).map(n => caches.delete(n))))
    .then(() => self.clients.claim()));
});
/* Cache first. The game never talks to a server, so anything it asks for is
   either in here or is not coming. */
self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then(hit => hit || fetch(e.request)));
});
